spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=2 # remove api/v1 from path
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
              filters:
                - StripPrefix=2 # remove api/v1 from path



#EUREKA CONFIG
eureka:
    instance:
      prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka