spring:
  application:
    name: api-gateway

  config:
    import: configserver:http://config-server:8888

#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/api/v1/orders/**
#              filters:
#                - StripPrefix=2 # remove api/v1 from path
#                - name: AuthorizationFilter
#                  args:
#                    enabled: true
#                    allowedRoles:
#                      - ADMIN
#                      - MANAGER
#            - id: inventory-service
#              uri: lb://INVENTORY-SERVICE
#              predicates:
#                - Path=/api/v1/inventory/**
#              filters:
#                - StripPrefix=2 # remove api/v1 from path
#                - name : InventoryLoggingFilter
#                - name : AuthenticationFilter
#                  args:
#                    enabled : true
#            - id: shipping-service
#              uri: lb://SHIPPING-SERVICE
#              predicates:
#                - Path=/api/v1/shipping/**
#              filters:
#                - StripPrefix=2 # remove api/v1 from path
#
#
#
##EUREKA CONFIG
#eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka

#jwt:
#  secretKey: secretbfrewhri34y7hjlnri3489hckjsnbp9478ytrewifbcuo347tr8few7her7htudsnfiu